### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shqnayaz** [jakubjastrabik/smartctl_ssacli_exporter#3]
Hi, 
Any guesses what I am missing, 
the exporter runs on port 9633, but when i try to curl localhost:9633/metrics,  i get the following runtime error 

```
root@compute# jobs
[1]+  Running                 ./smartctl_ssacli_exporter &


root@compute# curl http://localhost:9633/metrics
2022/08/29 16:29:38 http: panic serving 127.0.0.1:36890: runtime error: invalid memory address or nil pointer dereference
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc00014c780)
        /usr/lib/go/src/net/http/server.go:1772 +0x139
panic(0x917060, 0xe117f0)
        /usr/lib/go/src/runtime/panic.go:975 +0x3e3
github.com/prometheus/client_golang/prometheus.processMetric(0xa67120, 0xc000218e40, 0xc0001b55b8, 0xc0001b55e8, 0x0, 0x0, 0x0)
        /home/jastrabik/go/src/github.com/prometheus/client_golang/prometheus/registry.go:592 +0x51
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc0000e0730, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/jastrabik/go/src/github.com/prometheus/client_golang/prometheus/registry.go:517 +0xbe0
github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0x7f0625d6c118, 0xc00012a7d0, 0xc000154100)
        /home/jastrabik/go/src/github.com/prometheus/client_golang/prometheus/promhttp/http.go:126 +0x93
net/http.HandlerFunc.ServeHTTP(0xc00015e070, 0x7f0625d6c118, 0xc00012a7d0, 0xc000154100)
        /usr/lib/go/src/net/http/server.go:2012 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1(0x7f0625d6c118, 0xc00012a7d0, 0xc000154100)
        /home/jastrabik/go/src/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:40 +0xab
net/http.HandlerFunc.ServeHTTP(0xc00011a990, 0x7f0625d6c118, 0xc00012a7d0, 0xc000154100)
        /usr/lib/go/src/net/http/server.go:2012 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0xa6c7c0, 0xc0001640e0, 0xc000154100)
        /home/jastrabik/go/src/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:100 +0xda
net/http.HandlerFunc.ServeHTTP(0xc00011aa80, 0xa6c7c0, 0xc0001640e0, 0xc000154100)
        /usr/lib/go/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0xe22d20, 0xa6c7c0, 0xc0001640e0, 0xc000154100)
        /usr/lib/go/src/net/http/server.go:2387 +0x1a5
net/http.serverHandler.ServeHTTP(0xc000164000, 0xa6c7c0, 0xc0001640e0, 0xc000154100)
        /usr/lib/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc00014c780, 0xa6dd80, 0xc000146300)
        /usr/lib/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2933 +0x35c
curl: (52) Empty reply from server
```

**Comment by shqnayaz** [comment]
Its resolved, after installing smartmontools
